### PR TITLE
Trigger event when stop_all is call

### PR DESCRIPTION
**Pull request by vdeville**
For #5

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, thanks, @MyTheValentinus! Good catch. Could you remove it from `soundbox.jsm` though, please? I have a build script that automagically generates that file now.

**Comment by vdeville** [comment]
Ho yeah no problem. It's done

**Comment by sbrl** [comment]
Thanks! I'll merge it now, rebuild, and release v0.3.3.

**Comment by sbrl** [comment]
Cool, [v0.3.3](https://github.com/sbrl/soundbox/releases/tag/v0.3.3) is now a thing.

**Pull request merged**
