### PR TITLE
Add loop param to play() for soundInstance property

### PR DESCRIPTION
**Pull request by kdallas**
Since soundInstance instantiates HTML5 Audio (which inherits from HTMLMediaElement), a future revision could include a generic parameter for setting all supported properties, i.e.:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

However, for now I just wanted to add "loop" capability to my project so that is why only this property is being handled!

### CODE REVIEW

**Review by sbrl — APPROVED** [review]
Thanks, @kdallas! This looks great :D

Yeah, adding support for an options object might be a good idea, but not all the properties on HTMLMediaElement make sense in this context (e.g. `controls` is useless because we don't actually display anything to the user).

We'll have to think about the best approach there.

**Comment by kdallas** [comment]
Awesome thanks @sbrl, here's where I used it: https://www.weblabsperth.com.au/100-movies/

**Comment by sbrl** [comment]
Nice! I'll add this to the README under _Real-World Usage_ :D

**Comment by kdallas** [comment]
> Nice! I'll add this to the README under _Real-World Usage_ :D

sweet thanks man :)

**Pull request merged**
